// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.redhat.it.customers.dmc.core.dto.configuration.builder;

import com.redhat.it.customers.dmc.core.dto.configuration.AppConfiguration;
import com.redhat.it.customers.dmc.core.dto.configuration.Configuration;

/**
 * The Class ConfigurationBuilder.
 * 
 * @author Andrea Battaglia
 */
public class AppConfigurationBuilder extends
        ConfigurationBuilderBase<AppConfigurationBuilder> {
    
    private final AppConfiguration configuration;

    /**
     * Configuration.
     *
     * @return the configuration builder
     */
    public static AppConfigurationBuilder configuration() {
        return new AppConfigurationBuilder();
    }

    /**
     * Instantiates a new configuration builder.
     */
    public AppConfigurationBuilder() {
        configuration=new AppConfiguration();
    }

    /**
     * Builds the.
     *
     * @return the configuration
     */
    public Configuration build() {
        return getInstance();
    }
    @Override
    public Configuration getInstance() {
        return configuration;
    }
}

